version: "3.7"

services:
  db:
    image: postgres:13.14-alpine3.19
    container_name: postgres-desafio-rpe
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio-rpe
    ports:
      - "54322:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    image: maven:3.9-eclipse-temurin-21-alpine-desafio-rpe
    container_name: springboot-desafio-rpe
    environment:
      DATABASE_URL: jdbc:postgresql://postgres-desafio-rpe:5432/desafio-rpe
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "54321:8080"
    depends_on:
      - db