version: "3.7"

services:
  db:
    image: postgres:13.14-alpine3.19
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rpe
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  springboot:
    image: desafio-rpe
    container_name: desafio-rpe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/api
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    depends_on:
      - db
    ports:
      - "54621:80"
      - "443:443"