version: "3.7"

services:
  db:
    image: postgres:13.14-alpine3.19
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rpe
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  springboot:
    image: desafio-rpe
    container_name: desafio-rpe
    build:
      dockerfile_inline: |
        FROM eclipse-temurin:21-alpine
        WORKDIR /api
        COPY . .
        RUN apk add maven
        CMD ["DATABASE_URL=jdbc:postgresql://localhost:5432/rpe", "\", "DATABASE_USERNAME=postgres", "\", "DATABASE_PASSWORD=postgres", "\", "mvn", "spring-boot:run"]
    ports:
      - "8080:8080"
    volumes:
      - .:/api
    depends_on:
      - db